spring:
  config:
    activate:
      on-profile: prod

oci:
  auth:
    type: instance_principal

alert:
  oci-monitoring:
    mysql:
      db-systems:
        wafflestudio-mysql:
          thresholds:
            cpu-utilization:
              warning: 80.0
              critical: 90.0
            db-volume-utilization:
              warning: 80.0
              critical: 90.0
